# Generated by Django 5.1 on 2025-09-01 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('Apellido', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=250)),
                ('Direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('NTelefono', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSeguridad',
            fields=[
                ('idEmpresaSeguridad', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('Servicios', models.CharField(max_length=250)),
                ('Estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'EmpresaSeguridad',
            },
        ),
        migrations.CreateModel(
            name='EscalaAlerta',
            fields=[
                ('idEscalaIncidencia', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'EscalaAlerta',
            },
        ),
        migrations.CreateModel(
            name='EstadoAtencionReporte',
            fields=[
                ('idEstadoReporte', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'EstadoAtencionReporte',
            },
        ),
        migrations.CreateModel(
            name='PlanContrato',
            fields=[
                ('idPlanContrato', models.AutoField(primary_key=True, serialize=False)),
                ('TipoPlan', models.CharField(blank=True, max_length=100, null=True)),
                ('Monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'PlanContrato',
            },
        ),
        migrations.CreateModel(
            name='RolAutoridad',
            fields=[
                ('idRolAutoridad', models.AutoField(primary_key=True, serialize=False)),
                ('TipoAutoridad', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'RolAutoridad',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('idRolUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreRol', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'RolUsuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=250)),
                ('FechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idAlerta', models.AutoField(primary_key=True, serialize=False)),
                ('idCliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.cliente')),
            ],
            options={
                'db_table': 'Alerta',
            },
        ),
        migrations.CreateModel(
            name='DetalleAlerta',
            fields=[
                ('idTipoIncidencia', models.AutoField(primary_key=True, serialize=False)),
                ('Ubicacion', models.CharField(max_length=250)),
                ('Descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('FechaHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('idAlerta', models.ForeignKey(db_column='idAlerta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.alerta')),
                ('idEscalaIncidencia', models.ForeignKey(db_column='idEscalaIncidencia', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_escala', to='api.escalaalerta')),
            ],
            options={
                'db_table': 'DetalleAlerta',
            },
        ),
        migrations.CreateModel(
            name='DetalleEmpresa',
            fields=[
                ('idDetalleEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('NTelefono', models.CharField(blank=True, max_length=9, null=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=300, null=True)),
                ('RUC', models.CharField(blank=True, max_length=11, null=True)),
                ('idEmpresaSeguridad', models.ForeignKey(db_column='idEmpresaSeguridad', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.empresaseguridad')),
            ],
            options={
                'db_table': 'DetalleEmpresa',
            },
        ),
        migrations.CreateModel(
            name='AtencionReporte',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('FechaHoraAtencion', models.DateTimeField(default=django.utils.timezone.now)),
                ('idAdministrador', models.ForeignKey(db_column='idAdministrador', on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='api.administrador')),
                ('idTipoIncidencia', models.ForeignKey(db_column='idTipoIncidencia', on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='api.detallealerta')),
                ('idEstadoReporte', models.ForeignKey(db_column='idEstadoReporte', on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='api.estadoatencionreporte')),
                ('idRolAutoridad', models.ForeignKey(db_column='idRolAutoridad', on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='api.rolautoridad')),
            ],
            options={
                'db_table': 'AtencionReporte',
            },
        ),
        migrations.CreateModel(
            name='HistoriaAtencionReporte',
            fields=[
                ('idHistorialReporte', models.AutoField(primary_key=True, serialize=False)),
                ('idReporte', models.ForeignKey(db_column='idReporte', on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='api.atencionreporte')),
            ],
            options={
                'db_table': 'HistoriaAtencionReporte',
            },
        ),
        migrations.CreateModel(
            name='ContratoEmpresa',
            fields=[
                ('idContratoEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('FechaContrato', models.DateTimeField(default=django.utils.timezone.now)),
                ('idDetalleEmpresa', models.ForeignKey(db_column='idDetalleEmpresa', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='api.detalleempresa')),
                ('idPlanContrato', models.ForeignKey(db_column='idPlanContrato', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='api.plancontrato')),
            ],
            options={
                'db_table': 'ContratoEmpresa',
            },
        ),
        migrations.CreateModel(
            name='DetalleAutoridad',
            fields=[
                ('idDetalleAutoridad', models.AutoField(primary_key=True, serialize=False)),
                ('NTelefono', models.CharField(max_length=9)),
                ('Ubicacion', models.CharField(max_length=300)),
                ('idRolAutoridad', models.ForeignKey(db_column='idRolAutoridad', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.rolautoridad')),
            ],
            options={
                'db_table': 'DetalleAutoridad',
            },
        ),
        migrations.AddField(
            model_name='rolautoridad',
            name='idRolUsuario',
            field=models.ForeignKey(db_column='idRolUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='roles_autoridad', to='api.rolusuario'),
        ),
        migrations.AddField(
            model_name='empresaseguridad',
            name='idRolUsuario',
            field=models.ForeignKey(db_column='idRolUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='api.rolusuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idRolUsuario',
            field=models.ForeignKey(db_column='idRolUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.rolusuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='idRolUsuario',
            field=models.ForeignKey(db_column='idRolUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='api.rolusuario'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='idUsuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='api.usuario'),
        ),
    ]
