# Generated by Django 4.1 on 2025-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usua',
            },
        ),
    ]
