# Generated by Django 5.2.5 on 2025-09-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usua'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usua',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='FechaCreacion',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contra',
            field=models.CharField(db_column='contra', default='temporal123', max_length=250),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
