# Generated by Django 4.1 on 2025-09-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_usua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contra',
            field=models.CharField(db_column='contra', max_length=250),
        ),
    ]
