# Generated by Django 5.2.5 on 2025-09-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallealerta',
            name='NombreIncidente',
            field=models.CharField(default='Sin nombre', max_length=250),
            preserve_default=False,
        ),
    ]
