# Generated by Django 5.2.5 on 2025-09-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_detallealerta_nombreincidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallealerta',
            name='idAlerta',
            field=models.ForeignKey(blank=True, db_column='idAlerta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.alerta'),
        ),
        migrations.AlterField(
            model_name='detallealerta',
            name='idEscalaIncidencia',
            field=models.ForeignKey(blank=True, db_column='idEscalaIncidencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_escala', to='api.escalaalerta'),
        ),
    ]
