# Generated by Django 5.2.5 on 2025-09-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_detallealerta_idalerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallealerta',
            name='idUsuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.usuario'),
        ),
    ]
