# Generated by Django 5.2.6 on 2025-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallealerta',
            name='Escala',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], default=1),
        ),
    ]
