# Generated by Django 5.2.5 on 2025-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_detallealerta_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallealerta',
            name='Latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallealerta',
            name='Longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
