# Generated by Django 5.2.6 on 2025-10-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_detallealerta_latitud_detallealerta_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallealerta',
            name='Archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_alertas/'),
        ),
    ]
