# Generated by Django 5.2.6 on 2025-10-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_detallealerta_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaalerta',
            name='palabra_clave',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
