# Generated by Django 5.2.5 on 2025-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_escalaalerta_palabra_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallealerta',
            name='EstadoIncidente',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=20),
        ),
    ]
