# Generated by Django 5.1 on 2025-10-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_detallealerta_estadoincidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallealerta',
            name='Escala',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Pendiente (por asignar)')], default=1),
        ),
    ]
